/**
 * @fileoverview Writes the pieces every generated stylesheet is built from: a declaration, a
 * reference, a shadow's layers, a density's block. The emitters compose these, so what a
 * value looks like in CSS is settled in one place and a page that draws one step by hand
 * writes exactly what the stylesheet wrote.
 */

import { CONTROL_SIZES, controlHeights, type Density, type ShadowLayer } from '#scales.ts'

/**
 * Opens every generated stylesheet, so a reader knows not to edit it.
 */
export const HEADER = '/* Generated by @stealthscale/core-theme. Do not edit. */'

/**
 * Draws the light along the top edge of a raised surface, which every box shadow carries as
 * its first layer: transparent in light and a hairline of light in dark.
 */
const HIGHLIGHT = 'inset 0 1px 0 0 var(--shadow-highlight)'

/**
 * Writes one `--namespace-step: value;` line per step.
 *
 * @param {string} namespace - The namespace, without dashes.
 * @param {Readonly<Record<string, string>>} steps - Each step mapped to its value.
 * @returns {string} The lines, joined.
 */
export function lines(namespace: string, steps: Readonly<Record<string, string>>): string {
  return Object.entries(steps)
    .map(([step, value]) => `  --${namespace}-${step}: ${value};`)
    .join('\n')
}

/**
 * Writes one reference line per step: the theme layer names what a utility resolves, and the
 * theme's own stylesheet carries the value.
 *
 * @param {string} namespace - The namespace, without dashes.
 * @param {Readonly<Record<string, unknown>>} steps - The table, read for its step names.
 * @returns {string} The lines, joined.
 */
export function references(namespace: string, steps: Readonly<Record<string, unknown>>): string {
  return Object.keys(steps)
    .map((step) => `  --${namespace}-${step}: var(--${namespace}-${step});`)
    .join('\n')
}

/**
 * Writes one rule.
 *
 * @param {string} selector - The selector the rule applies to.
 * @param {readonly string[]} declarations - The declarations, without their semicolons.
 * @param {string} [indent] - The indent every line takes. Default: none.
 * @returns {string} The rule, with each declaration on a line of its own.
 */
export function rule(selector: string, declarations: readonly string[], indent = ''): string {
  const body = declarations.map((declaration) => `${indent}  ${declaration};`).join('\n')
  return `${indent}${selector} {\n${body}\n${indent}}`
}

/**
 * Writes one shadow layer, taking its share of the theme's shadow ink.
 *
 * @param {ShadowLayer} layer - The layer's geometry and share.
 * @param {string} [ink] - The variable the layer mixes from. Default: the theme's shadow ink.
 * @returns {string} The layer as CSS.
 */
function inked({ fraction, geometry }: ShadowLayer, ink = '--shadow'): string {
  return `${geometry} color-mix(in oklch, var(${ink}) ${String(fraction)}%, transparent)`
}

/**
 * Writes one box shadow as a `box-shadow` value: the raised edge's highlight, then every
 * layer drawn from the theme's shadow ink.
 *
 * @param {readonly ShadowLayer[]} layers - The step's layers, as `SHADOW` lists them.
 * @returns {string} The value, which reads the theme's own `--shadow` and
 *     `--shadow-highlight`.
 */
export function boxShadowOf(layers: readonly ShadowLayer[]): string {
  return [HIGHLIGHT, ...layers.map((layer) => inked(layer))].join(', ')
}

/**
 * Writes one glow as a `box-shadow` value, every layer thrown in the theme's glow colour.
 *
 * @param {readonly ShadowLayer[]} layers - The step's layers, as `GLOW` lists them.
 * @returns {string} The value, which reads the theme's own `--glow`.
 */
export function glowOf(layers: readonly ShadowLayer[]): string {
  return layers.map((layer) => inked(layer, '--glow')).join(', ')
}

/**
 * Writes one radius step as a multiple of the theme's one `--radius`.
 *
 * @param {number} factor - The step's factor, as `RADIUS` lists it.
 * @returns {string} The value, which reads the theme's own `--radius`.
 */
export function radiusOf(factor: number): string {
  return `calc(var(--radius) * ${String(factor)})`
}

/**
 * Writes a table of numbers as values, with a unit where the property takes one.
 *
 * @param {Readonly<Record<string, number>>} table - Each step mapped to its number.
 * @param {string} [unit] - The unit to append. Default: none, for a unitless property.
 * @returns {Record<string, string>} Each step mapped to its value as CSS.
 */
export function numbered(
  table: Readonly<Record<string, number>>,
  unit = '',
): Record<string, string> {
  return Object.fromEntries(
    Object.entries(table).map(([step, value]): [string, string] => [
      step,
      `${String(value)}${unit}`,
    ]),
  )
}

/**
 * Writes a table of shadow steps as values, each step's layers joined.
 *
 * @param {Readonly<Record<string, readonly ShadowLayer[]>>} table - Each step's layers.
 * @returns {Record<string, string>} Each step mapped to its value as CSS.
 */
export function stacked(
  table: Readonly<Record<string, readonly ShadowLayer[]>>,
): Record<string, string> {
  return Object.fromEntries(
    Object.entries(table).map(([step, layers]): [string, string] => [
      step,
      layers.map((layer) => inked(layer)).join(', '),
    ]),
  )
}

/**
 * Describes the densities one scope draws with.
 */
export interface Densities {
  /**
   * Names the density the scope itself takes, where nothing sets one.
   */
  fallback: string

  /**
   * Sets the focus ring's width, in pixels, which is one number for every density.
   */
  focusWidth: number

  /**
   * Maps each density to its one length and its focus offset.
   */
  steps: Readonly<Record<string, Density>>
}

/**
 * Writes one density's declarations: every control height it derives from its one length, and
 * where the focus ring sits outside a control.
 *
 * @param {Density} density - The density to write.
 * @returns {string[]} The declarations, without their semicolons.
 */
function densityDeclarations(density: Density): string[] {
  const heights = controlHeights(density)

  return [
    ...CONTROL_SIZES.map((step) => `--height-${step}: ${String(heights[step])}rem`),
    `--focus-offset: ${String(density.focusOffset)}px`,
  ]
}

/**
 * Writes what a scope draws with where nothing sets a density: the ring's width, which every
 * density shares, and the default density's own lengths.
 *
 * These sit in the block the scope already opens rather than a block of their own, so one
 * selector carries everything the scope declares.
 *
 * @param {Densities} densities - The densities the scope draws with.
 * @returns {string[]} The declarations, without their semicolons, and none where the scope's
 *     default density is not one it has.
 */
export function densityDefaults(densities: Densities): string[] {
  const taken = densities.steps[densities.fallback]
  if (taken === undefined) return []

  return [`--focus-width: ${String(densities.focusWidth)}px`, ...densityDeclarations(taken)]
}

/**
 * Writes one block per density, so a region can be denser or looser than the page around it.
 *
 * A scoped theme takes both forms of its own selector, the element that carries the theme and
 * anything below it, because a page that draws several themes puts the density on whichever
 * of the two a component reached for.
 *
 * @param {Densities} densities - The densities the scope draws with.
 * @param {string} scope - The selector the theme sits behind: `:root`, or `[data-theme='x']`.
 * @returns {string} The rules, joined.
 */
export function densityBlocks(densities: Densities, scope: string): string {
  return Object.entries(densities.steps)
    .map(([name, density]) => {
      const selector =
        scope === ':root'
          ? `[data-density='${name}']`
          : `${scope}[data-density='${name}'],\n${scope} [data-density='${name}']`
      return rule(selector, densityDeclarations(density))
    })
    .join('\n\n')
}
