/**
 * @fileoverview Writes the stylesheet a theme package ships. `:root` carries the light values
 * and `.dark` overrides them, which is the shape the `dark:` variant and every
 * `bg-background` expect. The theme layer nulls every namespace this package owns and
 * registers every step, so a utility nothing here defines renders nothing rather than
 * rendering Tailwind's default. The densities and the motion vocabulary are written here too,
 * each into a stylesheet of its own, because neither follows a palette and every theme shares
 * both. The custom variants and the base layer are the one part a theme still authors.
 */

import { safeParse } from '@stealthscale/core-schema'

import { assertComplete, assertReadable } from '#assert.ts'
import { ANIMATION, KEYFRAMES, PRESS_SCALE, SPINNING, STILL } from '#motion.ts'
import { buildPalette } from '#palette.ts'
import { levelOf, recipeSchema } from '#recipe.ts'
import {
  BLUR,
  CONTROL_SIZES,
  controlHeights,
  DEFAULT_DENSITY,
  DENSITY,
  type Density,
  DROP_SHADOW,
  DURATION,
  EASE,
  FOCUS_WIDTH,
  FONT_WEIGHT,
  GLOW,
  INSET_SHADOW,
  LEADING,
  OWNED_NAMESPACES,
  PERSPECTIVE,
  RADIUS,
  SHADOW,
  type ShadowLayer,
  TEXT,
  TEXT_SHADOW,
  TRACKING,
} from '#scales.ts'
import {
  COLOR_TOKENS,
  MODES,
  REQUIRED_TOKENS,
  type ThemeMode,
  type ThemeValues,
  type TokenName,
} from '#tokens.ts'

/**
 * Opens every generated stylesheet, so a reader knows not to edit it.
 */
export const HEADER = '/* Generated by @stealthscale/core-theme. Do not edit. */'

/**
 * Writes one `--token: value;` line per token, indented for the block it sits in.
 *
 * @param {ThemeValues} values - The theme.
 * @param {ThemeMode} mode - The mode whose values to write.
 * @returns {string} The lines, joined.
 */
function declarationLines(values: ThemeValues, mode: ThemeMode): string {
  return REQUIRED_TOKENS.map((token) => `  --${token}: ${values[mode][token]};`).join('\n')
}

/**
 * Writes the lines of one namespace from a table of steps.
 *
 * @param {string} namespace - The namespace, without dashes.
 * @param {Readonly<Record<string, string>>} steps - Each step mapped to its value.
 * @returns {string} The lines, joined.
 */
function lines(namespace: string, steps: Readonly<Record<string, string>>): string {
  return Object.entries(steps)
    .map(([step, value]) => `  --${namespace}-${step}: ${value};`)
    .join('\n')
}

/**
 * Draws the light along the top edge of a raised surface, which every box shadow carries as
 * its first layer: transparent in light and a hairline of light in dark.
 */
const HIGHLIGHT = 'inset 0 1px 0 0 var(--shadow-highlight)'

/**
 * Writes one shadow layer, taking its share of the theme's shadow ink.
 *
 * @param {ShadowLayer} layer - The layer's geometry and share.
 * @param {string} [ink] - The variable the layer mixes from. Default: the theme's shadow ink.
 * @returns {string} The layer as CSS.
 */
function layer({ fraction, geometry }: ShadowLayer, ink = '--shadow'): string {
  return `${geometry} color-mix(in oklch, var(${ink}) ${String(fraction)}%, transparent)`
}

/**
 * Writes one box shadow as a `box-shadow` value: the raised edge's highlight, then every
 * layer drawn from the theme's shadow ink.
 *
 * @param {readonly ShadowLayer[]} layers - The step's layers, as `SHADOW` lists them.
 * @returns {string} The value, which reads the theme's own `--shadow` and
 *     `--shadow-highlight`.
 */
export function boxShadowOf(layers: readonly ShadowLayer[]): string {
  return [HIGHLIGHT, ...layers.map((one) => layer(one))].join(', ')
}

/**
 * Writes one glow as a `box-shadow` value, every layer thrown in the theme's glow colour.
 *
 * @param {readonly ShadowLayer[]} layers - The step's layers, as `GLOW` lists them.
 * @returns {string} The value, which reads the theme's own `--glow`.
 */
export function glowOf(layers: readonly ShadowLayer[]): string {
  return layers.map((one) => layer(one, '--glow')).join(', ')
}

/**
 * Writes one radius step as a multiple of the theme's one `--radius`.
 *
 * @param {number} factor - The step's factor, as `RADIUS` lists it.
 * @returns {string} The value, which reads the theme's own `--radius`.
 */
export function radiusOf(factor: number): string {
  return `calc(var(--radius) * ${String(factor)})`
}

/**
 * Writes the box shadows and the glows.
 *
 * @returns {string} The lines, joined.
 */
function boxShadows(): string {
  const steps = Object.fromEntries([
    ...Object.entries(SHADOW).map(([step, layers]): [string, string] => [
      step,
      boxShadowOf(layers),
    ]),
    ...Object.entries(GLOW).map(([step, layers]): [string, string] => [
      `glow-${step}`,
      glowOf(layers),
    ]),
  ])
  return lines('shadow', steps)
}

/**
 * Writes a shadow namespace whose steps stack several layers, such as the drop shadows.
 *
 * @param {string} namespace - The namespace, without dashes.
 * @param {Readonly<Record<string, readonly ShadowLayer[]>>} table - Each step's layers.
 * @returns {string} The lines, joined.
 */
function layeredShadows(
  namespace: string,
  table: Readonly<Record<string, readonly ShadowLayer[]>>,
): string {
  const steps = Object.fromEntries(
    Object.entries(table).map(([step, layers]): [string, string] => [
      step,
      layers.map((one) => layer(one)).join(', '),
    ]),
  )
  return lines(namespace, steps)
}

/**
 * Writes a table of numbers as values, with a unit where the property takes one.
 *
 * @param {Readonly<Record<string, number>>} table - Each step mapped to its number.
 * @param {string} [unit] - The unit to append. Default: none, for a unitless property.
 * @returns {Record<string, string>} Each step mapped to its value as CSS.
 */
function numbered(table: Readonly<Record<string, number>>, unit = ''): Record<string, string> {
  return Object.fromEntries(
    Object.entries(table).map(([step, value]): [string, string] => [
      step,
      `${String(value)}${unit}`,
    ]),
  )
}

/**
 * Points every control step at the custom property a density sets, rather than at a length
 * fixed when the theme was built, so a utility resolves to whatever density the element sits
 * in. `size-*` reads the same property as `height-*`, because a square control is as wide as
 * it is tall.
 *
 * @returns {Record<string, string>} Each step mapped to the variable it reads.
 */
function controlSteps(): Record<string, string> {
  return Object.fromEntries(CONTROL_SIZES.map((step) => [step, `var(--height-${step})`]))
}

/**
 * Writes the type scale, each size with the line height that goes with it.
 *
 * @returns {string} The lines, joined.
 */
function typeScale(): string {
  return Object.entries(TEXT)
    .flatMap(([step, { lineHeight, size }]) => [
      `  --text-${step}: ${String(size)}rem;`,
      `  --text-${step}--line-height: calc(${String(lineHeight)} / ${String(size)});`,
    ])
    .join('\n')
}

/**
 * Writes the theme layer: every namespace nulled, then every step registered.
 *
 * `@theme inline` is what turns a variable into a utility: `--color-primary` is why
 * `bg-primary` exists. Each colour points at the theme's own variable, so a mode switch is a
 * variable change rather than a rebuild. Each radius is a multiple of the theme's one
 * `--radius`, and each shadow mixes from the theme's shadow ink, so a theme that changes
 * either changes every step. Breakpoints and containers are not here: those are a layout
 * decision, the same for every theme, and the design system's base sets them.
 *
 * @returns {string} The `@theme inline` block.
 */
function themeLayer(): string {
  const nulled = OWNED_NAMESPACES.map((namespace) => `  --${namespace}-*: initial;`).join('\n')
  const colors = COLOR_TOKENS.map((token) => `  --color-${token}: var(--${token});`).join('\n')
  const radii = Object.fromEntries(
    Object.entries(RADIUS).map(([step, factor]): [string, string] => [step, radiusOf(factor)]),
  )
  return `@theme inline {
${nulled}

  --color-white: #fff;
  --color-black: #000;
${colors}

  --font-sans: var(--font-sans);
  --font-mono: var(--font-mono);

${typeScale()}

${lines('font-weight', numbered(FONT_WEIGHT))}

${lines('tracking', numbered(TRACKING, 'em'))}

${lines('leading', numbered(LEADING))}

${lines('radius', radii)}

${boxShadows()}

${layeredShadows('inset-shadow', INSET_SHADOW)}

${layeredShadows('drop-shadow', DROP_SHADOW)}

${layeredShadows('text-shadow', TEXT_SHADOW)}

${lines('blur', numbered(BLUR, 'px'))}

${lines('perspective', numbered(PERSPECTIVE, 'px'))}

${lines('ease', EASE)}

${lines('height', controlSteps())}

${lines('size', controlSteps())}

${lines('duration', numbered(DURATION, 'ms'))}

  --default-transition-duration: var(--duration-normal);
  --default-transition-timing-function: var(--ease-out);
}`
}

/**
 * Writes the stylesheet a theme package ships, with the light values on `:root` and the dark
 * values under `.dark`.
 *
 * The stylesheet is imported unlayered. The font tokens share Tailwind's own key names, so
 * the theme layer's `--font-sans: var(--font-sans)` makes Tailwind emit a self-referencing
 * `--font-sans` inside `@layer theme`, and the theme's `:root` wins over it only because an
 * unlayered declaration beats a layered one. Imported into a cascade layer, the fonts fall
 * back to the browser's.
 *
 * @param {ThemeValues} values - The theme.
 * @returns {string} The stylesheet.
 */
export function emit(values: ThemeValues): string {
  return `${HEADER}
${themeLayer()}

:root {
  color-scheme: light;
${declarationLines(values, 'light')}
}

.dark {
  color-scheme: dark;
${declarationLines(values, 'dark')}
}
`
}

/**
 * Writes the same tokens scoped to a `data-theme` attribute instead of `:root`, and no theme
 * layer, because a document that holds several themes registers the layer once.
 *
 * A deployable links one theme, so `:root` is right there. A Storybook renders every theme in
 * one document and switches between them from a toolbar, which needs each theme's values
 * behind its own selector.
 *
 * @param {ThemeValues} values - The theme.
 * @param {string} name - The theme's name, as `data-theme` carries it.
 * @returns {string} The stylesheet.
 */
export function emitScoped(values: ThemeValues, name: string): string {
  return `${HEADER}
[data-theme='${name}'] {
  color-scheme: light;
${declarationLines(values, 'light')}
}

[data-theme='${name}'].dark,
.dark [data-theme='${name}'] {
  color-scheme: dark;
${declarationLines(values, 'dark')}
}
`
}

/**
 * Names the tokens a theme states itself, per mode, on top of what its recipe solves.
 *
 * A recipe is hues and a shape, and it answers for the relationships between tokens. It cannot
 * answer for a colour somebody else owns: a company whose blue is a fixed hex has one value the
 * palette may not move. Stating it here leaves every other token derived, so the label on that
 * fill, the ring around it and the ink beside it still follow.
 *
 * Anything stated is checked like anything solved. `assertReadable` runs after, so a colour its
 * own label cannot be read on fails the theme's build rather than the person using the product.
 */
export type StatedValues = Partial<Record<ThemeMode, Readonly<Partial<Record<TokenName, string>>>>>

/**
 * Lays a theme's own values over what its recipe solved.
 *
 * @param {ThemeValues} solved - The values the recipe built.
 * @param {Readonly<StatedValues>} stated - The values the theme states itself.
 * @param {string} name - The theme's name, for the message when a name is no token.
 * @returns {ThemeValues} The values to emit.
 * @throws {Error} When a stated name is no token of the contract, which is how a typo would
 *     otherwise pass unread and leave the solved value in place.
 */
function stateValues(
  solved: ThemeValues,
  stated: Readonly<StatedValues>,
  name: string,
): ThemeValues {
  const known = new Set<string>(REQUIRED_TOKENS)
  const unknown = MODES.flatMap((mode) =>
    Object.keys(stated[mode] ?? {})
      .filter((token) => !known.has(token))
      .map((token) => `${mode}.${token}`),
  )

  if (unknown.length > 0) {
    throw new Error(`Theme ${name} states what is no token: ${unknown.join(', ')}`)
  }

  return { dark: { ...solved.dark, ...stated.dark }, light: { ...solved.light, ...stated.light } }
}

/**
 * Describes everything a theme package writes out when it is built.
 */
export interface EmittedTheme {
  /**
   * Carries the stylesheet that claims `:root`, which an app links for the one theme it draws.
   */
  root: string

  /**
   * Carries the stylesheet behind `[data-theme]`, which a page drawing several themes at once
   * loads one of per theme.
   */
  scoped: string

  /**
   * Carries every token in both modes, for whatever reads a theme as data rather than as CSS.
   */
  values: ThemeValues
}

/**
 * Turns a theme's recipe into everything its package ships.
 *
 * A theme solves its palette once, where it is built, so no consumer carries the solver and
 * every one of them reads the same table. A recipe that cannot be drawn fails the theme's own
 * build, naming the field or the token, rather than failing a catalogue at boot or an app in
 * front of a person.
 *
 * @param {unknown} recipe - The recipe module's default export, as the package wrote it. It
 *     is held to the recipe schema before a palette is built from it.
 * @param {string} name - The value a document writes for this theme, which is the basename of
 *     the package's directory.
 * @param {Readonly<StatedValues>} [stated] - The tokens the theme states itself, which lie over
 *     what the recipe solved. `StatedValues` says when to reach for it. Default: none.
 * @returns {EmittedTheme} The two stylesheets and the solved values.
 * @throws {Error} When the recipe fails its schema, when a stated name is no token, or when a
 *     pair the theme promises falls below its floor. Each message names what is at fault.
 */
export function emitTheme(
  recipe: unknown,
  name: string,
  stated: Readonly<StatedValues> = {},
): EmittedTheme {
  const read = safeParse(recipeSchema(), recipe)
  if (!read.ok) {
    const reasons = read.failure.map((issue) => `${issue.path}: ${issue.reason}`)
    throw new Error(`Theme ${name} writes a recipe no palette builds from: ${reasons.join('; ')}`)
  }

  const values = stateValues(buildPalette(read.value), stated, name)
  assertComplete(values)
  assertReadable(values, levelOf(read.value))

  return { root: emit(values), scoped: emitScoped(values, name), values }
}

/**
 * Writes one density's declarations: every control height it derives from its one length, and
 * where the focus ring sits outside a control.
 *
 * @param {Density} density - The density to write, as `DENSITY` names it.
 * @returns {string} The declarations, joined, indented for the block they sit in.
 */
function densityDeclarations(density: Density): string {
  const heights = controlHeights(density)

  return [
    ...CONTROL_SIZES.map((step) => `  --height-${step}: ${String(heights[step])}rem;`),
    `  --focus-offset: ${String(density.focusOffset)}px;`,
  ].join('\n')
}

/**
 * Writes the densities, which every theme shares.
 *
 * A density is a property of the document rather than of a theme: the same three sizes hold
 * whatever palette is on, so this is emitted once by the theme other themes extend rather
 * than repeated in each. `:root` carries the default, so a page that sets no attribute still
 * draws controls, and every density has a block of its own so a region can be denser or
 * looser than the page around it.
 *
 * The ring's width is one number for every density: a ring that grew with the control would
 * be thinnest where controls sit closest together, which is where it is hardest to see.
 *
 * @returns {string} The stylesheet.
 */
export function emitDensities(): string {
  const entries = Object.entries(DENSITY)
  const fallback = entries
    .filter(([name]) => name === DEFAULT_DENSITY)
    .map(([, density]) => densityDeclarations(density))
    .join('\n')
  const blocks = entries.map(
    ([name, density]) => `[data-density='${name}'] {\n${densityDeclarations(density)}\n}`,
  )

  return `${HEADER}
:root {
  --focus-width: ${String(FOCUS_WIDTH)}px;
${fallback}
}

${blocks.join('\n\n')}
`
}

/**
 * Writes the Tailwind a stealth theme runs on: the framework, the animation library and the
 * plugins every theme has.
 *
 * It is a stylesheet of its own so `@plugin` can sit directly after the import that defines
 * it, before any theme's overrides. A CSS parser refuses an `@import` that follows another
 * at-rule, so a single file listing the framework, the plugins and then the theme's own
 * stylesheets is not possible: the plugin would have to come last, after everything it is
 * meant to sit under.
 *
 * `tw-animate-css` is the default an app gets before any theme speaks: the `animate-in` and
 * `animate-out` composition and the utilities that modify a running animation. The motion
 * stylesheet loads after it and overrides by name, so a theme decides what `animate-fade-in`
 * means without taking the rest away.
 *
 * @returns {string} The stylesheet.
 */
export function emitTailwind(): string {
  return `${HEADER}
@import 'tailwindcss';
@import 'tw-animate-css';
@plugin '@tailwindcss/typography';
`
}

/**
 * Writes one animation's keyframes.
 *
 * @param {string} name - The animation's name, which its `--animate-*` step runs.
 * @param {Readonly<Record<string, readonly string[]>>} offsets - The declarations at each
 *     offset, as `KEYFRAMES` holds them.
 * @returns {string} The `@keyframes` rule.
 */
function keyframes(name: string, offsets: Readonly<Record<string, readonly string[]>>): string {
  const steps = Object.entries(offsets)
    .map(([offset, declarations]) => {
      const body = declarations.map((declaration) => `    ${declaration};`).join('\n')
      return `  ${offset} {\n${body}\n  }`
    })
    .join('\n')

  return `@keyframes ${name} {\n${steps}\n}`
}

/**
 * Writes one rule.
 *
 * @param {string} selector - The selector the rule applies to.
 * @param {readonly string[]} declarations - The declarations, without their semicolons.
 * @param {string} [indent] - The indent every line takes. Default: none.
 * @returns {string} The rule, with each declaration on a line of its own.
 */
function rule(selector: string, declarations: readonly string[], indent = ''): string {
  const body = declarations.map((declaration) => `${indent}  ${declaration};`).join('\n')
  return `${indent}${selector} {\n${body}\n${indent}}`
}

/**
 * Writes the policy a person asking for reduced motion gets.
 *
 * The attribute answers as well as the media query, so the path can be reviewed on demand
 * rather than only on a machine configured for it.
 *
 * @returns {string} The rules, in both forms.
 */
function stillness(): string {
  const everything = '*,\n*::before,\n*::after'
  const attribute =
    '[data-reduced-motion],\n[data-reduced-motion] *,\n' +
    '[data-reduced-motion] *::before,\n[data-reduced-motion] *::after'

  return `@media (prefers-reduced-motion: reduce) {
${rule(':root', ['--press-scale: 1'], '  ')}

${rule(everything, STILL, '  ')}

${rule("[data-slot='spinner']", SPINNING, '  ')}
}

${rule(attribute, STILL)}

${rule("[data-reduced-motion] [data-slot='spinner']", SPINNING)}`
}

/**
 * Writes the motion vocabulary: every animation as a step of the `animate` namespace, the
 * keyframes those steps run, and what a person asking for reduced motion gets instead.
 *
 * It is a stylesheet of its own because a keyframe is a top-level rule and cannot sit inside
 * the theme layer, and because the vocabulary is the same whatever a recipe solves to: one
 * theme writes it and every theme extending that one imports it. The reduced-motion policy is
 * here rather than in a theme's own base because it overrides `--press-scale`, and a rule that
 * loads before the declaration it overrides does nothing.
 *
 * The `animate` namespace is not nulled, which is why it is absent from `OWNED_NAMESPACES`.
 * Tailwind and `tw-animate-css` load first and their names stay reachable; these are declared
 * after and win where they collide, so a theme states what `animate-fade-in` means and leaves
 * `animate-in`, `animate-bounce` and the modifier utilities where a component found them.
 *
 * @returns {string} The stylesheet.
 */
export function emitMotion(): string {
  const frames = Object.entries(KEYFRAMES)
    .map(([name, offsets]) => keyframes(name, offsets))
    .join('\n\n')

  return `${HEADER}

@theme {
  --press-scale: ${String(PRESS_SCALE)};

${lines('animate', ANIMATION)}
}

${frames}

${stillness()}
`
}
