/**
 * @fileoverview Writes the stylesheet a theme package ships. `:root` carries the light values
 * and `.dark` overrides them, which is the shape the `dark:` variant and every
 * `bg-background` expect. The theme layer nulls every namespace this package owns and
 * registers every step, so a utility nothing here defines renders nothing rather than
 * rendering Tailwind's default. Keyframes, the custom variants and the densities are
 * authored CSS the design system ships, which every theme's stylesheet imports first.
 */

import { safeParse } from '@stealthscale/core-schema'

import { assertComplete } from '#assert.ts'
import { buildPalette } from '#palette.ts'
import { recipeSchema } from '#recipe.ts'
import {
  BLUR,
  DROP_SHADOW,
  DURATION,
  EASE,
  FONT_WEIGHT,
  GLOW,
  INSET_SHADOW,
  LEADING,
  OWNED_NAMESPACES,
  PERSPECTIVE,
  RADIUS,
  SHADOW,
  type ShadowLayer,
  TEXT,
  TEXT_SHADOW,
  TRACKING,
} from '#scales.ts'
import { COLOR_TOKENS, REQUIRED_TOKENS, type ThemeMode, type ThemeValues } from '#tokens.ts'

/**
 * Opens every generated stylesheet, so a reader knows not to edit it.
 */
const HEADER = '/* Generated by @stealthscale/core-theme. Do not edit. */'

/**
 * Writes one `--token: value;` line per token, indented for the block it sits in.
 *
 * @param {ThemeValues} values - The theme.
 * @param {ThemeMode} mode - The mode whose values to write.
 * @returns {string} The lines, joined.
 */
function declarationLines(values: ThemeValues, mode: ThemeMode): string {
  return REQUIRED_TOKENS.map((token) => `  --${token}: ${values[mode][token]};`).join('\n')
}

/**
 * Writes the lines of one namespace from a table of steps.
 *
 * @param {string} namespace - The namespace, without dashes.
 * @param {Readonly<Record<string, string>>} steps - Each step mapped to its value.
 * @returns {string} The lines, joined.
 */
function lines(namespace: string, steps: Readonly<Record<string, string>>): string {
  return Object.entries(steps)
    .map(([step, value]) => `  --${namespace}-${step}: ${value};`)
    .join('\n')
}

/**
 * Draws the light along the top edge of a raised surface, which every box shadow carries as
 * its first layer: transparent in light and a hairline of light in dark.
 */
const HIGHLIGHT = 'inset 0 1px 0 0 var(--shadow-highlight)'

/**
 * Writes one shadow layer, taking its share of the theme's shadow ink.
 *
 * @param {ShadowLayer} layer - The layer's geometry and share.
 * @param {string} [ink] - The variable the layer mixes from. Default: the theme's shadow ink.
 * @returns {string} The layer as CSS.
 */
function layer({ fraction, geometry }: ShadowLayer, ink = '--shadow'): string {
  return `${geometry} color-mix(in oklch, var(${ink}) ${String(fraction)}%, transparent)`
}

/**
 * Writes one box shadow as a `box-shadow` value: the raised edge's highlight, then every
 * layer drawn from the theme's shadow ink.
 *
 * @param {readonly ShadowLayer[]} layers - The step's layers, as `SHADOW` lists them.
 * @returns {string} The value, which reads the theme's own `--shadow` and
 *     `--shadow-highlight`.
 */
export function boxShadowOf(layers: readonly ShadowLayer[]): string {
  return [HIGHLIGHT, ...layers.map((one) => layer(one))].join(', ')
}

/**
 * Writes one glow as a `box-shadow` value, every layer thrown in the theme's glow colour.
 *
 * @param {readonly ShadowLayer[]} layers - The step's layers, as `GLOW` lists them.
 * @returns {string} The value, which reads the theme's own `--glow`.
 */
export function glowOf(layers: readonly ShadowLayer[]): string {
  return layers.map((one) => layer(one, '--glow')).join(', ')
}

/**
 * Writes one radius step as a multiple of the theme's one `--radius`.
 *
 * @param {number} factor - The step's factor, as `RADIUS` lists it.
 * @returns {string} The value, which reads the theme's own `--radius`.
 */
export function radiusOf(factor: number): string {
  return `calc(var(--radius) * ${String(factor)})`
}

/**
 * Writes the box shadows and the glows.
 *
 * @returns {string} The lines, joined.
 */
function boxShadows(): string {
  const steps = Object.fromEntries([
    ...Object.entries(SHADOW).map(([step, layers]): [string, string] => [
      step,
      boxShadowOf(layers),
    ]),
    ...Object.entries(GLOW).map(([step, layers]): [string, string] => [
      `glow-${step}`,
      glowOf(layers),
    ]),
  ])
  return lines('shadow', steps)
}

/**
 * Writes a shadow namespace whose steps stack several layers, such as the drop shadows.
 *
 * @param {string} namespace - The namespace, without dashes.
 * @param {Readonly<Record<string, readonly ShadowLayer[]>>} table - Each step's layers.
 * @returns {string} The lines, joined.
 */
function layeredShadows(
  namespace: string,
  table: Readonly<Record<string, readonly ShadowLayer[]>>,
): string {
  const steps = Object.fromEntries(
    Object.entries(table).map(([step, layers]): [string, string] => [
      step,
      layers.map((one) => layer(one)).join(', '),
    ]),
  )
  return lines(namespace, steps)
}

/**
 * Writes a table of numbers as values, with a unit where the property takes one.
 *
 * @param {Readonly<Record<string, number>>} table - Each step mapped to its number.
 * @param {string} [unit] - The unit to append. Default: none, for a unitless property.
 * @returns {Record<string, string>} Each step mapped to its value as CSS.
 */
function numbered(table: Readonly<Record<string, number>>, unit = ''): Record<string, string> {
  return Object.fromEntries(
    Object.entries(table).map(([step, value]): [string, string] => [
      step,
      `${String(value)}${unit}`,
    ]),
  )
}

/**
 * Writes the type scale, each size with the line height that goes with it.
 *
 * @returns {string} The lines, joined.
 */
function typeScale(): string {
  return Object.entries(TEXT)
    .flatMap(([step, { lineHeight, size }]) => [
      `  --text-${step}: ${String(size)}rem;`,
      `  --text-${step}--line-height: calc(${String(lineHeight)} / ${String(size)});`,
    ])
    .join('\n')
}

/**
 * Writes the theme layer: every namespace nulled, then every step registered.
 *
 * `@theme inline` is what turns a variable into a utility: `--color-primary` is why
 * `bg-primary` exists. Each colour points at the theme's own variable, so a mode switch is a
 * variable change rather than a rebuild. Each radius is a multiple of the theme's one
 * `--radius`, and each shadow mixes from the theme's shadow ink, so a theme that changes
 * either changes every step. Breakpoints and containers are not here: those are a layout
 * decision, the same for every theme, and the design system's base sets them.
 *
 * @returns {string} The `@theme inline` block.
 */
function themeLayer(): string {
  const nulled = OWNED_NAMESPACES.map((namespace) => `  --${namespace}-*: initial;`).join('\n')
  const colors = COLOR_TOKENS.map((token) => `  --color-${token}: var(--${token});`).join('\n')
  const radii = Object.fromEntries(
    Object.entries(RADIUS).map(([step, factor]): [string, string] => [step, radiusOf(factor)]),
  )
  return `@theme inline {
${nulled}

  --color-white: #fff;
  --color-black: #000;
${colors}

  --font-sans: var(--font-sans);
  --font-mono: var(--font-mono);

${typeScale()}

${lines('font-weight', numbered(FONT_WEIGHT))}

${lines('tracking', numbered(TRACKING, 'em'))}

${lines('leading', numbered(LEADING))}

${lines('radius', radii)}

${boxShadows()}

${layeredShadows('inset-shadow', INSET_SHADOW)}

${layeredShadows('drop-shadow', DROP_SHADOW)}

${layeredShadows('text-shadow', TEXT_SHADOW)}

${lines('blur', numbered(BLUR, 'px'))}

${lines('perspective', numbered(PERSPECTIVE, 'px'))}

${lines('ease', EASE)}

${lines('duration', numbered(DURATION, 'ms'))}

  --default-transition-duration: var(--duration-normal);
  --default-transition-timing-function: var(--ease-out);
}`
}

/**
 * Writes the stylesheet a theme package ships, with the light values on `:root` and the dark
 * values under `.dark`.
 *
 * The stylesheet is imported unlayered. The font tokens share Tailwind's own key names, so
 * the theme layer's `--font-sans: var(--font-sans)` makes Tailwind emit a self-referencing
 * `--font-sans` inside `@layer theme`, and the theme's `:root` wins over it only because an
 * unlayered declaration beats a layered one. Imported into a cascade layer, the fonts fall
 * back to the browser's.
 *
 * @param {ThemeValues} values - The theme.
 * @returns {string} The stylesheet.
 */
export function emit(values: ThemeValues): string {
  return `${HEADER}
${themeLayer()}

:root {
  color-scheme: light;
${declarationLines(values, 'light')}
}

.dark {
  color-scheme: dark;
${declarationLines(values, 'dark')}
}
`
}

/**
 * Writes the same tokens scoped to a `data-theme` attribute instead of `:root`, and no theme
 * layer, because a document that holds several themes registers the layer once.
 *
 * A deployable links one theme, so `:root` is right there. A Storybook renders every theme in
 * one document and switches between them from a toolbar, which needs each theme's values
 * behind its own selector.
 *
 * @param {ThemeValues} values - The theme.
 * @param {string} name - The theme's name, as `data-theme` carries it.
 * @returns {string} The stylesheet.
 */
export function emitScoped(values: ThemeValues, name: string): string {
  return `${HEADER}
[data-theme='${name}'] {
  color-scheme: light;
${declarationLines(values, 'light')}
}

[data-theme='${name}'].dark,
.dark [data-theme='${name}'] {
  color-scheme: dark;
${declarationLines(values, 'dark')}
}
`
}

/**
 * Describes everything a theme package writes out when it is built.
 */
export interface EmittedTheme {
  /**
   * Carries the stylesheet that claims `:root`, which an app links for the one theme it draws.
   */
  root: string

  /**
   * Carries the stylesheet behind `[data-theme]`, which a page drawing several themes at once
   * loads one of per theme.
   */
  scoped: string

  /**
   * Carries every token in both modes, for whatever reads a theme as data rather than as CSS.
   */
  values: ThemeValues
}

/**
 * Turns a theme's recipe into everything its package ships.
 *
 * A theme solves its palette once, where it is built, so no consumer carries the solver and
 * every one of them reads the same table. A recipe that cannot be drawn fails the theme's own
 * build, naming the field or the token, rather than failing a catalogue at boot or an app in
 * front of a person.
 *
 * @param {unknown} recipe - The recipe module's default export, as the package wrote it. It
 *     is held to the recipe schema before a palette is built from it.
 * @param {string} name - The value a document writes for this theme, which is the basename of
 *     the package's directory.
 * @returns {EmittedTheme} The two stylesheets and the solved values.
 * @throws {Error} When the recipe fails its schema, naming every field at fault.
 */
export function emitTheme(recipe: unknown, name: string): EmittedTheme {
  const read = safeParse(recipeSchema(), recipe)
  if (!read.ok) {
    const reasons = read.failure.map((issue) => `${issue.path}: ${issue.reason}`)
    throw new Error(`Theme ${name} writes a recipe no palette builds from: ${reasons.join('; ')}`)
  }

  const values = buildPalette(read.value)
  assertComplete(values)

  return { root: emit(values), scoped: emitScoped(values, name), values }
}
